version: "3.9"

services:
  ditm:
    image: ditm
    container_name: raft-m-ditm
    hostname: ditm
    environment:
      CONTAINER_HOST_NAMES: raft-m-1,raft-m-2,raft-m-3,raft-m-4,raft-m-5
    volumes:
      - ./volumes/volumes:/volumes
      - ./volumes/recordings:/recordings
      - ./volumes/snapshots:/snapshots
    ports:
      - "8000:80"
      - "5000:5000"
    depends_on:
      - raft-m-1
      - raft-m-2
      - raft-m-3
      - raft-m-4
      - raft-m-5
  
  raft-m-1:
    image: simple-raft-mongo
    container_name: raft-m-1
    hostname: raft-m-1
    environment: 
      - HTTP_PROXY=ditm:5000
      - RAFT_ID=1
      - RAFT_FORCE_LEADER=true
      - RAFT_PEERS={"2":"raft-m-2", "3":"raft-m-3", "5":"raft-m-5", "4":"raft-m-4"}
    logging:
      driver: jonathanarns/http-log-driver
      options:
        endpoint: http://localhost:8000/log

  raft-m-2:
    image: simple-raft-mongo
    container_name: raft-m-2
    hostname: raft-m-2
    environment: 
      - HTTP_PROXY=ditm:5000
      - RAFT_ID=2
      - RAFT_PEERS={"1":"raft-m-1", "3":"raft-m-3", "5":"raft-m-5", "4":"raft-m-4"}
    logging:
      driver: jonathanarns/http-log-driver
      options:
        endpoint: http://localhost:8000/log

  raft-m-3:
    image: simple-raft-mongo
    container_name: raft-m-3
    hostname: raft-m-3
    environment: 
      - HTTP_PROXY=ditm:5000
      - RAFT_ID=3
      - RAFT_PEERS={"1":"raft-m-1", "2":"raft-m-2", "5":"raft-m-5", "4":"raft-m-4"}
    logging:
      driver: jonathanarns/http-log-driver
      options:
        endpoint: http://localhost:8000/log

  raft-m-4:
    image: simple-raft-mongo
    container_name: raft-m-4
    hostname: raft-m-4
    environment: 
      - HTTP_PROXY=ditm:5000
      - RAFT_ID=4
      - RAFT_PEERS={"1":"raft-m-1", "2":"raft-m-2", "3":"raft-m-3", "5":"raft-m-5"}
    logging:
      driver: jonathanarns/http-log-driver
      options:
        endpoint: http://localhost:8000/log

  raft-m-5:
    image: simple-raft-mongo
    container_name: raft-m-5
    hostname: raft-m-5
    environment: 
      - HTTP_PROXY=ditm:5000
      - RAFT_ID=5
      - RAFT_PEERS={"1":"raft-m-1", "2":"raft-m-2", "3":"raft-m-3", "4":"raft-m-4"}
    logging:
      driver: jonathanarns/http-log-driver
      options:
        endpoint: http://localhost:8000/log
