version: "3.9"

services:
  ditm:
    image: ditm
    container_name: st-ditm
    hostname: ditm
    environment:
      CONTAINER_HOST_NAMES: tm,ae,ae2,mm
    volumes:
      - ./volumes/volumes:/volumes
      - ./volumes/recordings:/recordings
      - ./volumes/snapshots:/snapshots
    ports:
      - "8000:80"
      - "5000:5000"
    depends_on:
      - tm
      - ae
      - ae2
      - mm
  
  tm:
    image: tenant-management:ditm
    container_name: tm
    hostname: tm
    ports:
      - "8080:8000"
    environment: 
      - HTTP_PROXY=http://ditm:5000
      - ATOMIC_ENGINE_API_URL=atomic-engine
      - MEASURES_API_URL=measures-microservice
      # don't worry, all of these are not production secrets
      - ATOMIC_ENGINE_API_KEY=KDUJNBpb.dyfr46g91s9GYq9oiPf8rD1pN8mlmg0W
      - MEASURES_API_KEY=smFUFEq1.R1aB90jEw2FNxADcgNmXxTztjatlnWaY
      - JWT_SIGNING_KEY=abcdefghijklmnopqrxtuvwxyz
      - DEBUG=True
      - ENVIRONMENT=development
      - DJANGO_SETTINGS_MODULE=tenant_management.settings.development
    volumes:
      - ./volumes/volumes/tm:/db
    logging:
      driver: jonathanarns/http-log-driver
      options:
        endpoint: http://localhost:8000/log

  ae:
    image: atomic-engine:ditm
    container_name: ae
    hostname: ae
    ports:
      - "8081:8000"
    environment: 
      - HTTP_PROXY=http://ditm:5000
      - JWT_SIGNING_KEY=abcdefghijklmnopqrxtuvwxyz
      - DEBUG=True
      - ENVIRONMENT=development
      - DJANGO_SETTINGS_MODULE=atomic_engine.settings.development
    volumes:
      - ./volumes/volumes/ae:/db
    logging:
      driver: jonathanarns/http-log-driver
      options:
        endpoint: http://localhost:8000/log

  ae2:
    image: atomic-engine2:ditm
    container_name: ae2
    hostname: ae2
    ports:
      - "8082:80"
    environment: 
      - HTTP_PROXY=http://ditm:5000
      - JWT_SIGNING_KEY=abcdefghijklmnopqrxtuvwxyz
      - DEBUG=True
      - ENVIRONMENT=development
      - DJANGO_SETTINGS_MODULE=atomic_engine_2.settings.development
      - TENANT_MANAGEMENT_DOMAIN=tm:8000
    volumes:
      - ./volumes/volumes/ae2:/db
    logging:
      driver: jonathanarns/http-log-driver
      options:
        endpoint: http://localhost:8000/log

  mm:
    image: measures-microservice:ditm
    container_name: mm
    hostname: mm
    ports:
      - "8083:8000"
    environment: 
      - HTTP_PROXY=http://ditm:5000
      - JWT_SIGNING_KEY=abcdefghijklmnopqrxtuvwxyz
      - DEBUG=True
      - ENVIRONMENT=development
      - DJANGO_SETTINGS_MODULE=measures_microservice.settings.development
    volumes:
      - ./volumes/volumes/mm:/db
    logging:
      driver: jonathanarns/http-log-driver
      options:
        endpoint: http://localhost:8000/log

