version: "3.9"

services:
  ditm:
    image: ditm
    container_name: syn-ditm
    hostname: ditm
    environment:
      CONTAINER_HOST_NAMES: target,target2
    volumes:
      - ./volumes/volumes:/volumes
      - ./volumes/recordings:/recordings
      - ./volumes/snapshots:/snapshots
    ports:
      - "8000:80"
      - "5000:5000"
    depends_on:
      - target
      - target2
  
  target:
    image: synthetic-target
    container_name: syn-target
    hostname: target
    ports:
      - "8080:80"
    environment: 
      - HTTP_PROXY=ditm:5000
      - PEER=target2
    logging:
      driver: jonathanarns/http-log-driver
      options:
        endpoint: http://localhost:8000/log

  target2:
    image: synthetic-target
    container_name: syn-target2
    hostname: target2
    ports:
      - "8081:80"
    environment: 
      - HTTP_PROXY=ditm:5000
      - PEER=target
    logging:
      driver: jonathanarns/http-log-driver
      options:
        endpoint: http://localhost:8000/log
