version: "3.9"

services:
  fuzznet:
    image: fuzznet
    container_name: fuzznet
    hostname: fuzznet
    ports:
      - "8000:81"
      - "5000:80"
  
  target:
    build: ./hello_world
    container_name: target
    ports:
      - "8080:80"
    environment: 
      - HTTP_PROXY=fuzznet:80
